<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\Material;
use App\Services\SignedUrlService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class MaterialController extends Controller
{
    public function download(Request $request, Material $material, SignedUrlService $signer): RedirectResponse
    {
        $this->authorize('download', $material);

        $url = $signer->forMaterial($material, $request->user(), $request, 'attachment');

        return redirect()->away($url);
    }

    /**
     * Branded viewer page that embeds the PDF and offers a Download button.
     * For non-PDF materials this just bounces to the external URL.
     */
    public function view(Request $request, Material $material, SignedUrlService $signer): View|RedirectResponse
    {
        $this->authorize('download', $material);

        if ($material->type !== Material::TYPE_PDF) {
            return redirect()->away($material->external_url ?? url('/'));
        }

        $inlineUrl = $signer->forMaterial($material, $request->user(), $request, 'inline');

        return view('student.materials.view', [
            'material' => $material,
            'pdfUrl' => $inlineUrl,
        ]);
    }

    /**
     * Local-dev placeholder shown when a seeded material has no real R2 file.
     */
    public function demoPlaceholder(Request $request, Material $material): View
    {
        if (! $request->hasValidSignature()) {
            abort(403);
        }

        return view('student.materials.demo-placeholder', ['material' => $material]);
    }

    /**
     * Local-dev streaming endpoint that serves the uploaded PDF either
     * inline (for the embedded viewer iframe) or as an attachment (for the
     * explicit Download button). Production uses signed CDN URLs from
     * R2/S3 instead — this is only hit when FILESYSTEM_DISK=local. Auth is
     * via a time-limited signed URL generated by SignedUrlService.
     */
    public function demoStream(Request $request, Material $material): StreamedResponse
    {
        if (! $request->hasValidSignature()) {
            abort(403);
        }

        $disk = Storage::disk(config('filesystems.default'));

        if (! $material->file_path || ! $disk->exists($material->file_path)) {
            abort(404);
        }

        $filename = $material->title.'.pdf';
        $disposition = $request->query('disposition') === 'attachment' ? 'attachment' : 'inline';

        return $disk->response($material->file_path, $filename, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => $disposition.'; filename="'.$filename.'"',
        ]);
    }
}
