<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use App\Models\Material;
use App\Models\Submission;
use App\Services\SignedUrlService;
use App\Support\PrivateFile;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class MaterialController extends Controller
{
    public function download(Request $request, Material $material, SignedUrlService $signer): RedirectResponse
    {
        $this->authorize('download', $material);

        $url = $signer->forMaterial($material, 'attachment');

        return redirect()->away($url);
    }

    /**
     * Branded viewer page that embeds the PDF and offers a Download button.
     * For non-PDF materials this just bounces to the external URL.
     */
    public function view(Request $request, Material $material, SignedUrlService $signer): View|RedirectResponse
    {
        $this->authorize('download', $material);

        if ($material->type === Material::TYPE_PAGE) {
            return view('student.materials.page', ['material' => $material]);
        }

        if ($material->type === Material::TYPE_ASSIGNMENT) {
            $course = $material->section->course;
            $user = $request->user();
            $isTeacherOrAdmin = $user->teaches($course) || $user->hasRole('admin');

            if ($isTeacherOrAdmin) {
                $students = $course->students()
                    ->wherePivot('is_active', true)
                    ->orderBy('users.name')
                    ->get();

                $submissions = Submission::with([
                    'files' => fn ($q) => $q->orderBy('uploaded_at'),
                    'feedbackFiles' => fn ($q) => $q->orderBy('uploaded_at'),
                ])
                    ->where('material_id', $material->id)
                    ->get()
                    ->keyBy('user_id');

                return view('teacher.materials.assignment', [
                    'material' => $material,
                    'students' => $students,
                    'submissions' => $submissions,
                ]);
            }

            $submission = Submission::with([
                'files' => fn ($q) => $q->orderBy('uploaded_at'),
                'feedbackFiles' => fn ($q) => $q->orderBy('uploaded_at'),
            ])
                ->where('material_id', $material->id)
                ->where('user_id', $user->id)
                ->first();

            return view('student.materials.assignment', [
                'material' => $material,
                'submission' => $submission,
            ]);
        }

        if ($material->type !== Material::TYPE_PDF) {
            return redirect()->away($material->external_url ?? url('/'));
        }

        $inlineUrl = $signer->forMaterial($material, 'inline');

        return view('student.materials.view', [
            'material' => $material,
            'pdfUrl' => $inlineUrl,
        ]);
    }

    /**
     * Local-dev placeholder shown when a seeded material has no real R2 file.
     */
    public function demoPlaceholder(Request $request, Material $material): View
    {
        if (! $request->hasValidSignature()) {
            abort(403);
        }

        return view('student.materials.demo-placeholder', ['material' => $material]);
    }

    /**
     * Local-dev streaming endpoint that serves the uploaded PDF either
     * inline (for the embedded viewer iframe) or as an attachment (for the
     * explicit Download button). Production uses signed CDN URLs from
     * R2/S3 instead — this is only hit when FILESYSTEM_DISK=local. Auth is
     * via a time-limited signed URL generated by SignedUrlService.
     */
    public function demoStream(Request $request, Material $material): StreamedResponse
    {
        if (! $request->hasValidSignature()) {
            abort(403);
        }

        if (! PrivateFile::exists($material->file_path)) {
            abort(404);
        }

        $disposition = $request->query('disposition') === 'attachment' ? 'attachment' : 'inline';

        // Signature verified above — PrivateFile::response does no checks.
        return PrivateFile::response(
            $material->file_path,
            $material->title.'.pdf',
            'application/pdf',
            $disposition,
        );
    }
}
